-- Add missing columns to rooms table
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS turn_order JSONB;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS turn_index INTEGER DEFAULT 0;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS recap_image_url TEXT;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS winner TEXT;
ALTER TABLE rooms ADD COLUMN IF NOT EXISTS is_private BOOLEAN DEFAULT false;
